// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainChecklist.Data;

namespace TrainChecklist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200103210923_TworzenieBazy")]
    partial class TworzenieBazy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrainChecklist.DomainModels.Pojazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IloscWagonow")
                        .HasColumnType("int");

                    b.Property<int>("NumerPojazdu")
                        .HasColumnType("int");

                    b.Property<string>("TypPojazdu")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ListaPojazdowWBazie");
                });
#pragma warning restore 612, 618
        }
    }
}
